### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by yonas44**
Thank you for reviewing my PR!

### CODE REVIEW

**Comment by Trust-007** [comment]
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @yonas44 , I'm @Trust-007, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

so-close-gif-4

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:
- Awesome code structure ✔️ 

## Required Changes ♻️

- [x] You did a great job in your use of good semantics but please make sure that your class names are always lowercase to follow the HTML and CSS best practices :+1: 
https://github.com/yonas44/Repo_to_be_Reviewed/blob/134e00832e52e19024952ef4c75c677442efa50f/src/index.html#L18

- [x] Your index.js looks great and has less code but try to use the `const` scope to ensure that your variable doesn't get changed later on.
https://github.com/yonas44/Repo_to_be_Reviewed/blob/134e00832e52e19024952ef4c75c677442efa50f/src/index.js#L8

- [x]  Please try to use the YAGNI principle in your code to keep neat and simple
https://github.com/yonas44/Repo_to_be_Reviewed/blob/134e00832e52e19024952ef4c75c677442efa50f/src/modules/taskLoader.js#L29-L30

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


- [OPTIONAL][x] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by yonas44** [comment]
Okay thank you for your feedback @Trust-007

**Review by Trust-007 — APPROVED** [review]
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @yonas44   , I'm @Trust-007  , your reviewer for this PR  :wave: 
Great work on making the changes requested by a previous reviewer 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 





## Highlights
- Descriptive pull request :heavy_check_mark:👨🏻‍💻
- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [ ] Check the comments under the review.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Cheers and Happy coding! 🤓 👏👏👏

**Comment by yonas44** [comment]
Thank you @Trust-007 I will proceed with the merge!

**Pull request merged**
